###
### Default configuration
###

version: "3.3"

networks:
  default:

services:
  postfix:
    image: ${DOCKER_IMAGE}
    # command: bash
    # stdin_open: true
    # tty: true
    depends_on:
      - simple_ca
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=postfix.local
      - SIMPLE_CA_URL=https://simple-ca.local
      - POSTFIX_MYHOSTNAME=host.example.com
      - POSTFIX_MYNETWORKS=192.0.2.0/24
      - POSTFIX_RELAY_DOMAINS=example.com .example.com
      - POSTFIX_RELAY_HOST=[relay.example.com]
      - POSTFIX_TRANSPORT=example.com=relay:[relay.example.com] .example.com=relay:[relay.example.com]
      - POSTFIX_SASL_PASSWD=relay.example.com=relay:P@ssw0rd.
      - POSTFIX_ROOT_ALIAS=root@example.com
      - POSTFIX_MESSAGE_SIZE_LIMIT=1000000
      - POSTFIX_RSPAMD_MILTER=inet:rspamd.local:11332
      - POSTFIX_DNSSEC=yes
      # - POSTFIX_RSPAMD_MILTER=inet:rspamd.local:11332
    networks:
      default:
        aliases:
          - postfix.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}

  simple_ca:
    image: ${SIMPLE_CA_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=simple-ca.local
    networks:
      default:
        aliases:
          - simple-ca.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_data:/var/lib/simple-ca
      - simple_ca_secrets:/var/lib/simple-ca/secrets

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - postfix
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - WAIT_FOR_TCP=postfix.local:25
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - postfix
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - WAIT_FOR_TCP=postfix.local:25
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  test_project_dir:
  simple_ca_data:
  simple_ca_secrets:
